dist: bionic
language: java

matrix:
  include:
    - jdk: oraclejdk8
      dist: trusty
    - jdk: openjdk8
      dist: trusty
    - jdk: oraclejdk11
    - jdk: openjdk11

script: mvn jacoco:prepare-agent test verify jacoco:report -B -Pintegration-test -DrepoToken=$coveralls_repo_token

after_success:
  - mvn coveralls:report
