dist: trusty
language: java
jdk:
  - oraclejdk8

script: mvn jacoco:prepare-agent test verify jacoco:report -B -Pintegration-test -DrepoToken=$coveralls_repo_token

after_success:
  - mvn coveralls:report
